/* Interaction director. All personal messages stay on-device until WhatsApp opens. */
(() => {
'use strict';
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],D=window.ASSYABAB_CONTENT;
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n)),mix=(a,b,t)=>a+(b-a)*t;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pref=matchMedia('(prefers-reduced-motion: reduce)');let reduced=pref.matches,paused=false,lastFocus=null,cinema=null,land=null,dayland=null,dirty=true,film=null,lastTime=0,clock=0,lastPaint=0,toastTimer,resizeTimer;
const metrics={video:false,errors:[],frames:0,cinemaProgress:0,day:0};
window.AssyababDebug={metrics,scene:()=>cinema,renderAt:(p)=>{if(cinema){cinema.seekProgress(p);updateShot(p);metrics.cinemaProgress=p;}},stopFilm:()=>stopFilm()};
const header=$('.header'),menu=$('#chapter-menu'),menuButton=$('.menu-button'),info=$('#information-modal'),search=$('#search-modal'),photo=$('#photo-modal');
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),4000);}
function scrollToTarget(hash){let target=document.getElementById(hash.replace(/^#/,''));if(!target)return;target.scrollIntoView({behavior:reduced||paused?'instant':'smooth',block:'start'});target.setAttribute('tabindex','-1');target.focus({preventScroll:true});try{history.replaceState(null,'',hash);}catch{/* Standalone about:blank preview has no navigation origin. */}}
function setMenu(open){menu.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Tutup daftar bab':'Buka daftar bab');$('main').inert=open;$('.brand').inert=open;$('.header-nav').inert=open;$('.search-open').inert=open;$('.experience-controls').inert=open;document.body.classList.toggle('locked',open||$$('dialog[open]').length>0);header.classList.toggle('fixed',open||scrollY>85);if(open){stopFilm();$('a',menu)?.focus();}else{menuButton.focus({preventScroll:true});}}
menuButton.addEventListener('click',()=>setMenu(menu.hidden));
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a||e.defaultPrevented)return;const target=document.getElementById(a.hash.slice(1));if(!target)return;e.preventDefault();stopFilm();scrollToTarget(a.hash);});

$$('a[href^="#"]',menu).forEach(a=>a.addEventListener('click',e=>{e.preventDefault();setMenu(false);scrollToTarget(a.hash);}));
document.addEventListener('keydown',e=>{
 if(e.key==='Escape'){stopFilm();if(!menu.hidden)setMenu(false);}
 if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(search.open)search.close();else openSearch();}
 if(e.key==='Tab'&&!menu.hidden){let items=[menuButton,...$$('a',menu)];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0].focus();}}
});
function dialogOpen(dialog){stopFilm();if(!dialog.open){lastFocus=document.activeElement;dialog.showModal();}document.body.classList.add('locked');}
for(const dialog of [info,search,photo]){
 dialog.addEventListener('close',()=>{document.body.classList.toggle('locked',!menu.hidden||$$('dialog[open]').length>0);if(!$$('dialog[open]').length&&lastFocus?.isConnected)lastFocus.focus({preventScroll:true});dirty=true;});
 dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
}
$('[data-close-modal]').addEventListener('click',()=>info.close());$('[data-close-search]').addEventListener('click',()=>search.close());$('.photo-close').addEventListener('click',()=>photo.close());
function openInfo(html){$('#modal-content').innerHTML=html;dialogOpen(info);info.scrollTop=0;}
function openVision(){openInfo(`<span class="modal-eyebrow">ARAH PENDIDIKAN / SLIDE 11–12</span><h2 id="modal-title">Ilmu dengan<br><em>sebuah tujuan.</em></h2><p class="vision-quote">“${escapeHTML(D.vision)}”</p><span class="eyebrow">MISI ASSYABAB</span><ol>${D.missions.map(s=>`<li>${escapeHTML(s)}</li>`).join('')}</ol>`);}
function openCurriculum(){openInfo(`<span class="modal-eyebrow">PROGRAM PENDIDIKAN / SLIDE 14–16</span><h2 id="modal-title">Ruang belajar<br>yang <em>utuh.</em></h2><p>Sepuluh kelompok pembelajaran berikut melengkapi program 4T Al-Qur’an. Susunan tampilan bukan urutan kelulusan.</p><div class="curriculum-grid">${D.curriculum.map((r,i)=>`<article><small>${String(i+1).padStart(2,'0')}</small><h3>${escapeHTML(r[0])}</h3><p>${escapeHTML(r[1])}</p>${r[2]?`<p class="reference">${escapeHTML(r[2])}</p>`:''}</article>`).join('')}</div><p style="margin-top:30px">Evaluasi melalui Ujian Madrasah dan Ujian Pesantren, disertai musyawarah pengembangan berkala sebagaimana disebutkan pada materi profil.</p>`);}
function openPeople(){openInfo(`<span class="modal-eyebrow">PENGELOLA & PENGAJAR / SLIDE 5–9</span><h2 id="modal-title">Ilmu yang tumbuh<br>lewat <em>teladan.</em></h2><div class="people-list">${Object.entries(D.people).map(([id,p])=>`<button type="button" data-person="${id}"><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.role)} ↗</p></button>`).join('')}</div><p style="font-size:12px;margin-top:24px">Jabatan dan latar belakang mengikuti materi profil; perubahan susunan dikonfirmasi kepada pesantren.</p>`);}
function openPerson(id){const p=D.people[id];if(!p)return;openInfo(`<span class="modal-eyebrow">PENGAJAR ASSYABAB / MATERI PROFIL SLIDE ${p.slide}</span><h2 id="modal-title">${escapeHTML(p.name)}</h2><span class="person-role">${escapeHTML(p.role.toUpperCase())}${p.degree?' · '+escapeHTML(p.degree):''}</span><p class="person-description">${escapeHTML(p.description)}</p><button class="text-button" data-open-people style="margin-top:32px">Kembali ke seluruh pengajar <span>↗</span></button>`);}
function openSources(){openInfo(`<div class="source-info"><span class="modal-eyebrow">CATATAN KARYA / TRANSPARANSI SUMBER</span><h2 id="modal-title">Satu sumber.<br><em>Interpretasi baru.</em></h2><p>Sumber fakta dan dokumentasi: <strong>${escapeHTML(D.source)}</strong>, diberikan pemilik proyek. Profil berasal dari slide 1–3; pengelola 5–9; visi-misi 11–12; program 14–16; fasilitas 18–27; metode, kompetensi, dan sosial 28–30; rutinitas 31; akademik 32; film 33; brosur kontak 34; dukungan 35.</p><h3>Foto dan ilustrasi dibedakan.</h3><p>Foto kegiatan, fasilitas, dan potret berasal dari materi tersebut. Lanskap bergerak dan film Al-Qur’an menuju ruang multimedia adalah ilustrasi artistik. Film berasal dari materi video yang diberikan pemilik proyek; bukan dokumentasi kampus. Suara air dibuat secara sintetis untuk membangun suasana. Bukan rekonstruksi bangunan, peta geografis, maupun reproduksi halaman mushaf. Tulisan kecil pada film ilustrasi tidak digunakan sebagai materi bacaan atau rujukan ayat.</p><h3>Ini prototipe presentasi.</h3><p>Jabatan, kontak, penyelenggaraan ijazah, biaya, kuota, bantuan, dan periode penerimaan perlu dikonfirmasi sebelum peluncuran resmi. Izin penggunaan foto juga perlu persetujuan pengelola. Kalimat editorial dan identitas visual merupakan usulan desain, bukan slogan atau logo resmi yang diklaim sudah disahkan.</p><h3>Fitur dengan batas yang jelas.</h3><p>Studio pesan mengekspor simulasi gambar di perangkat Anda. Formulir menyusun draf WhatsApp; tidak menerima pendaftaran, menyimpan nama, mengirim pesan otomatis, maupun memesan kunjungan. Tidak ada pelacakan atau layanan AI berbayar.</p></div>`);}
function openContact(kind='pendaftaran'){
 const visit=kind==='kunjungan';openInfo(`<span class="modal-eyebrow">BICARA LANGSUNG DENGAN PENGELOLA</span><h2 id="modal-title">${visit?'Mari berkunjung.<br><em>Mari mengenal.</em>':'Sebuah langkah.<br><em>Banyak kemungkinan.</em>'}</h2><p>Susun pesan untuk Ustadz Riyadi Lubis. Pesan belum dikirim sampai Anda membukanya dan menekan kirim di WhatsApp.</p><form class="contact-form" id="contact-form" data-kind="${kind}"><label for="contact-name">Nama Anda <span aria-hidden="true">*</span><input id="contact-name" name="name" maxlength="80" required autocomplete="name" placeholder="Nama wali / pengunjung"></label><label for="contact-message">${visit?'Rencana kunjungan / pertanyaan':'Pertanyaan tentang pendidikan'}<textarea id="contact-message" name="message" maxlength="1000" rows="3" placeholder="${visit?'Tuliskan rencana hari kunjungan dan hal yang ingin ditanyakan.':'Tuliskan hal yang ingin Anda ketahui.'}"></textarea></label><button class="primary-button" type="submit">Pratinjau pesan <span>↗</span></button><p class="contact-privacy">Data hanya digunakan untuk menyusun pesan di perangkat ini. Tidak disimpan ke server. ${visit?'Kunjungan belum terjadwal sebelum pengelola menyetujuinya.':'Formulir ini bukan formulir penerimaan santri.'}</p><div id="contact-result" hidden><div class="contact-preview"></div><a class="contact-link" target="_blank" rel="noopener noreferrer">Buka draf di WhatsApp <span>↗</span></a><p class="contact-privacy">WhatsApp akan terbuka di tab atau aplikasi lain. Anda tetap meninjau dan mengirim pesannya sendiri.</p></div></form>`);
 $('#contact-form').addEventListener('submit',e=>{e.preventDefault();let name=$('#contact-name').value.trim(),message=$('#contact-message').value.trim();if(!name){$('#contact-name').setCustomValidity('Nama tidak boleh hanya berisi spasi.');$('#contact-name').reportValidity();return;}let text=`Assalamu'alaikum, saya ${name}. Saya ingin ${visit?'menanyakan rencana kunjungan ke':'mengetahui informasi pendaftaran di'} Pesantren Multimedia Assyabab.${message?'\n\n'+message:''}\n\nTerima kasih.`;let result=$('#contact-result');$('.contact-preview',result).textContent=text;$('.contact-link',result).href=`https://wa.me/${D.contact}?text=${encodeURIComponent(text)}`;result.hidden=false;$('.contact-link',result).focus({preventScroll:true});result.scrollIntoView({behavior:reduced?'instant':'smooth',block:'nearest'});});
 $('#contact-name').addEventListener('input',e=>e.target.setCustomValidity(''));
 for(let input of $$('#contact-form input, #contact-form textarea'))input.addEventListener('input',()=>{$('#contact-result').hidden=true;});
}
document.addEventListener('click',e=>{let button=e.target.closest('button');if(!button)return;if(button.hasAttribute('data-open-vision'))openVision();if(button.hasAttribute('data-open-curriculum'))openCurriculum();if(button.hasAttribute('data-open-people'))openPeople();if(button.hasAttribute('data-person'))openPerson(button.dataset.person);if(button.hasAttribute('data-open-contact'))openContact(button.dataset.openContact);if(button.hasAttribute('data-open-sources'))openSources();});
// Search uses a fixed, source-grounded index. No generated answers or network call.
const normal=s=>s.toLocaleLowerCase('id').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function renderSearch(){const words=normal($('#search-input').value.trim()).split(/\s+/).filter(Boolean);const rows=D.search.filter(r=>words.every(word=>normal(r.join(' ')).includes(word))).slice(0,8);let results=$('#search-results');results.replaceChildren();if(!rows.length){let p=document.createElement('p');p.textContent='Belum ada informasi yang cocok. Coba “program”, “asrama”, atau “pendaftaran”.';results.append(p);return;}for(let row of rows){let b=document.createElement('button');b.className='search-result';let span=document.createElement('span');span.textContent=row[0];let small=document.createElement('small');small.textContent=row[1];span.append(small);let i=document.createElement('i');i.textContent='↗';i.setAttribute('aria-hidden','true');b.append(span,i);b.addEventListener('click',()=>{search.close();if(row[2].startsWith('#'))scrollToTarget(row[2]);else setTimeout(()=>({curriculum:openCurriculum,people:openPeople,contact:()=>openContact(),visit:()=>openContact('kunjungan'),vision:openVision,sources:openSources}[row[2]]?.()),0);});results.append(b);}}
function openSearch(){if(!menu.hidden)setMenu(false);$('#search-input').value='';renderSearch();dialogOpen(search);$('#search-input').focus();}
$('.search-open').addEventListener('click',openSearch);$('#search-input').addEventListener('input',renderSearch);$('#search-input').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){$('.search-result')?.focus();e.preventDefault();}});
// Native details preserve reading and keyboard behavior if JavaScript is unavailable.
const programs=$$('.program-list details');let lastProgram=-1;
function updateProgram(){let i=programs.findIndex(x=>x.open);if(i===lastProgram)return;lastProgram=i;$('#program-index').textContent=i>=0?String(i+1).padStart(2,'0')+' — 04':'4T / AL-QUR’AN';$('#program-name').textContent=i>=0?$('summary>span',programs[i]).textContent:'Saling melengkapi';$('.program-symbol svg').style.transform=`rotate(${Math.max(i,0)*45}deg)`;dirty=true;}
for(const d of programs)d.addEventListener('toggle',()=>{if(d.open)programs.forEach(other=>{if(other!==d)other.open=false;});updateProgram();});updateProgram();
function selectDay(index){index=clamp(index,0,3);let day=D.days[index];metrics.day=index;$$('[data-day]').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',String(i===index));});$('.daily').style.setProperty('--day',index);$('.day-index').textContent=String(index+1).padStart(2,'0')+' / '+day.name.toUpperCase();$('#day-title').replaceChildren(...day.title.split('\n').flatMap((s,i)=>i?[document.createElement('br'),document.createTextNode(s)]:[document.createTextNode(s)]));$('#day-copy').textContent=day.copy;$('#day-tags').replaceChildren(...day.tags.map(t=>{let span=document.createElement('span');span.textContent=t;return span;}));if(dayland){dayland.setDay(index);dayland.render(clock);}dirty=true;}
$$('[data-day]').forEach((b,i)=>{b.addEventListener('click',()=>selectDay(i));b.addEventListener('keydown',e=>{let n=e.key==='ArrowRight'?(i+1)%4:e.key==='ArrowLeft'?(i+3)%4:e.key==='Home'?0:e.key==='End'?3:null;if(n!==null){e.preventDefault();selectDay(n);$$('[data-day]')[n].focus();}});});
const track=$('.gallery-track'),cards=$$('.gallery-card');let galleryIndex=0;
function updateGallery(){const left=track.getBoundingClientRect().left+parseFloat(getComputedStyle(track).paddingLeft);galleryIndex=cards.map((c,i)=>[Math.abs(c.getBoundingClientRect().left-left),i]).sort((a,b)=>a[0]-b[0])[0][1];$('#gallery-counter').textContent=String(galleryIndex+1).padStart(2,'0')+' — 05';$('#gallery-prev').disabled=track.scrollLeft<3;$('#gallery-next').disabled=track.scrollLeft+track.clientWidth>=track.scrollWidth-4;}
function shiftGallery(direction){const i=clamp(galleryIndex+direction,0,cards.length-1),left=cards[i].getBoundingClientRect().left-track.getBoundingClientRect().left+track.scrollLeft-parseFloat(getComputedStyle(track).paddingLeft);track.scrollTo({left,behavior:reduced||paused?'instant':'smooth'});}
$('#gallery-prev').addEventListener('click',()=>shiftGallery(-1));$('#gallery-next').addEventListener('click',()=>shiftGallery(1));track.addEventListener('scroll',updateGallery,{passive:true});track.addEventListener('keydown',e=>{if(e.target===track&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();shiftGallery(e.key==='ArrowLeft'?-1:1);}});updateGallery();
let photoIndex=0;function showPhoto(index){photoIndex=(index+D.gallery.length)%D.gallery.length;const r=D.gallery[photoIndex];let img=$('#lightbox-image');img.src=cards[photoIndex].querySelector('img').src;img.alt=r.title;$('#lightbox-caption').textContent=String(photoIndex+1).padStart(2,'0')+' / 05 — '+r.title+'. '+r.caption;dialogOpen(photo);}
cards.forEach((b,i)=>b.addEventListener('click',()=>showPhoto(i)));$('.photo-prev').addEventListener('click',()=>showPhoto(photoIndex-1));$('.photo-next').addEventListener('click',()=>showPhoto(photoIndex+1));photo.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();showPhoto(photoIndex+(e.key==='ArrowLeft'?-1:1));}});
// The poster tool is rendered entirely locally, avoiding cross-origin canvas taint.
const poster=$('#composition'),pc=poster.getContext('2d');let palette=0;
const posterPalettes=[['#adc2b4','#436861','#173c40','#f5ebd1'],['#ddba90','#a06e58','#392e34','#f9edd6'],['#6d8995','#345464','#142c3c','#e1e6d8']];
function drawPoster(){if(!pc)return;const c=pc,w=poster.width,h=poster.height,cols=posterPalettes[palette];let gr=c.createLinearGradient(0,0,w,h);gr.addColorStop(0,cols[0]);gr.addColorStop(.62,cols[1]);gr.addColorStop(1,cols[2]);c.fillStyle=gr;c.fillRect(0,0,w,h);for(let k=0;k<5;k++){c.beginPath();c.moveTo(0,h);for(let x=0;x<=w;x+=3){let u=x/w,y=h*(.66+k*.053-.11*Math.sin(u*4+k*.25)+.025*Math.sin(u*12+k)+.006*Math.sin(u*71));c.lineTo(x,y);}c.lineTo(w,h);c.closePath();c.fillStyle=cols[2];c.globalAlpha=.13+k*.08;c.fill();}c.globalAlpha=1;c.strokeStyle=cols[3]+'52';c.lineWidth=1;c.strokeRect(38,38,w-76,h-76);c.beginPath();c.arc(w*.78,h*.28,145,0,Math.PI*2);c.stroke();c.beginPath();c.arc(w*.78,h*.28,126,0,Math.PI*2);c.stroke();c.fillStyle=cols[3];c.font='14px Arial';c.fillText('ASSYABAB  /  RUANG BERKARYA',76,92);c.font='16px Arial';c.fillText('SEBUAH PESAN UNTUK DITERUSKAN',76,190);
 let text=$('#poster-title').value.trim()||'Ilmu yang menjadi kebaikan.';$('#poster-count').textContent=$('#poster-title').value.length;let size=94,lines=[];const wrap=(fontSize)=>{c.font=`${fontSize}px Georgia`;let ls=[],line='';for(let word of text.split(/\s+/)){if(c.measureText(word).width>1030){for(let ch of word){if(c.measureText(line+ch).width>1030){ls.push(line);line=ch;}else line+=ch;}continue;}let test=line?line+' '+word:word;if(c.measureText(test).width>1030&&line){ls.push(line);line=word;}else line=test;}if(line)ls.push(line);return ls;};lines=wrap(size);while(lines.length>3&&size>42){size-=3;lines=wrap(size);}let y=280;lines.forEach((line,i)=>{c.font=`${i===lines.length-1?'italic ':''}${size}px Georgia`;c.fillText(line,76,y);y+=size*1.08;});c.font='italic 36px Georgia';c.fillText('Dari ruang mengaji, menuju dunia.',76,650);c.font='12px Arial';c.fillText('SIMULASI DESAIN · BUKAN KARYA SANTRI ASLI',76,716);c.font='15px Arial';c.textAlign='right';c.fillText(['FAJAR','SENJA','MALAM'][palette],w-76,716);c.textAlign='left';}
$('#poster-title').addEventListener('input',drawPoster);$$('[data-palette]').forEach((b,i)=>b.addEventListener('click',()=>{palette=i;$$('[data-palette]').forEach((x,j)=>{x.classList.toggle('active',i===j);x.setAttribute('aria-pressed',String(i===j));});drawPoster();}));
$('#export-poster').addEventListener('click',()=>{try{drawPoster();poster.toBlob(blob=>{if(!blob){toast('Gambar belum dapat dibuat. Coba sekali lagi.');return;}let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Assyabab-Komposisi.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Komposisi PNG sudah dibuat untuk disimpan.');},'image/png');}catch{toast('Ekspor tidak tersedia pada browser ini.');}});drawPoster();
// Scene setup and one shared animation loop, with no hidden scene rendering.
try{land=new window.AssyababLandscape($('#landscape'));land.render(0);}catch(e){metrics.errors.push('Landscape: '+e.message);}
try{dayland=new window.AssyababLandscape($('#day-landscape'),813);dayland.render(0);}catch(e){metrics.errors.push('Daily: '+e.message);}
cinema=new window.AssyababScrollFilm($('#cinema-video'),$('#cahaya'));
const cinematic=$('#cahaya'),hero=$('#beranda'),daySection=$('#kehidupan');let heroVisible=true,cinemaVisible=false,dayVisible=false;
if('IntersectionObserver'in window){let observer=new IntersectionObserver(entries=>{for(let e of entries){if(e.target===hero)heroVisible=e.isIntersecting;if(e.target===cinematic)cinemaVisible=e.isIntersecting;if(e.target===daySection)dayVisible=e.isIntersecting;}dirty=true;},{rootMargin:'60px'});[hero,cinematic,daySection].forEach(s=>observer.observe(s));}else{heroVisible=cinemaVisible=dayVisible=true;}
let currentShot=-1;
function updateShot(p){
 const s=p<.38?0:p<.62?1:2;if(s===currentShot)return;currentShot=s;
 $$('[data-shot]').forEach((x,i)=>{x.classList.toggle('is-active',i===s);x.setAttribute('aria-hidden',String(i!==s));});
 $$('[data-shot-jump]').forEach((x,i)=>{x.classList.toggle('active',i===s);x.setAttribute('aria-pressed',String(i===s));});
 $('#scene-label').textContent=['SUMBER DARI SETIAP LANGKAH','RUANG UNTUK BERTUMBUH','ILMU MENEMUKAN MEDIUMNYA'][s];
}
function jumpShot(index){stopFilm();const p=[.02,.50,.96][index];if(reduced||paused){cinema.seekProgress(p);updateShot(p);}else window.scrollTo({top:cinematic.offsetTop+p*(cinematic.offsetHeight-innerHeight),behavior:'smooth'});}
$$('[data-shot-jump]').forEach((b,i)=>b.addEventListener('click',()=>jumpShot(i)));
function stopFilm(){if(!film)return;film=null;$$('[data-play-film]').forEach(b=>{b.innerHTML='<span class="play-symbol">▷</span> Putar perjalanan <small>± 35 detik</small>';b.setAttribute('aria-pressed','false');});}
function startFilm(){if(reduced||paused){scrollToTarget('#cahaya');toast('Gerak dijeda. Pilih bab untuk menjelajahi film.');return;}if(film){stopFilm();return;}window.scrollTo({top:0,behavior:'instant'});film={start:performance.now(),hiddenAt:null};$$('[data-play-film]').forEach(b=>{b.innerHTML='<span class="play-symbol">Ⅱ</span> Hentikan perjalanan';b.setAttribute('aria-pressed','true');});toast('Perjalanan dimulai. Gulir, sentuh, atau tekan Escape untuk berhenti.');}
$$('[data-play-film]').forEach(b=>b.addEventListener('click',startFilm));window.addEventListener('wheel',stopFilm,{passive:true});window.addEventListener('touchstart',stopFilm,{passive:true});window.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End',' '].includes(e.key)&&!e.target.matches('input,textarea'))stopFilm();});
function applyMotion(){const wasInFilm=cinematic.getBoundingClientRect().top<=0&&cinematic.getBoundingClientRect().bottom>=innerHeight;const wasStatic=document.body.classList.contains("cinema-static");if(reduced||paused)stopFilm();document.body.classList.toggle("cinema-static",reduced);if(wasInFilm&&wasStatic!==reduced)window.scrollTo({top:cinematic.offsetTop+cinema.progress*Math.max(0,cinematic.offsetHeight-innerHeight),behavior:"instant"});document.body.classList.toggle('reduced-motion',reduced||paused);document.documentElement.classList.toggle('js-motion',!reduced&&!paused);$('#motion-toggle').setAttribute('aria-pressed',String(reduced||paused));$('#motion-toggle').setAttribute('aria-label',paused?'Lanjutkan animasi':'Jeda animasi dekoratif');$('.control-label').textContent=reduced?'Minim gerak':paused?'Gerak dijeda':'Jeda gerak';$('.motion-icon').textContent=paused?'▷':'Ⅱ';dirty=true;}
$('#motion-toggle').addEventListener('click',()=>{paused=!paused;applyMotion();});pref.addEventListener?.('change',e=>{reduced=e.matches;applyMotion();});applyMotion();
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Layar penuh tidak didukung browser ini.');}catch{toast('Browser tidak mengizinkan layar penuh.');}});document.addEventListener('fullscreenchange',()=>$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Keluar dari layar penuh':'Buka layar penuh'));
if('IntersectionObserver'in window){const reveal=new IntersectionObserver(entries=>{for(let e of entries)if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target);}},{threshold:.05,rootMargin:'0px 0px 25px 0px'});$$('[data-reveal]').forEach(e=>reveal.observe(e));}else{$$('[data-reveal]').forEach(e=>e.classList.add('visible'));}
const chapters=[['beranda','00'],['cahaya','01'],['pendidikan','02'],['studio','03'],['kehidupan','04'],['pengajar','05'],['ruang','06'],['bergabung','07']];
function onScroll(){dirty=true;const y=scrollY;header.classList.toggle('fixed',y>85||!menu.hidden);$('.experience-controls').classList.toggle('shown',y>innerHeight*.5);const range=document.documentElement.scrollHeight-innerHeight;$('.reading-progress').style.transform=`scaleX(${range>0?clamp(y/range):0})`;let active='00';for(let [id,index] of chapters)if($('#'+id).getBoundingClientRect().top<innerHeight*.45)active=index;$('#chapter-now').textContent=active;}
function refreshLayout(){clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{land?.resize();dayland?.resize();cinema?.resize();updateGallery();onScroll();dirty=true;},160);}
window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',refreshLayout,{passive:true});
// Observe settled CSS dimensions as well as window resize: viewport units may update later.
if('ResizeObserver'in window){const resizeObserver=new ResizeObserver(refreshLayout);[hero,$('.cinema-sticky'),daySection].forEach(element=>resizeObserver.observe(element));}
window.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||reduced||paused)return;const p=[(e.clientX/innerWidth-.5)*2,(e.clientY/innerHeight-.5)*2];if(land)land.pointer=p;if(cinema)cinema.pointer=p;},{passive:true});
function tick(now){requestAnimationFrame(tick);const dt=Math.min((now-lastTime)/1000,.1)||0;lastTime=now;if(document.hidden)return;if(!reduced&&!paused)clock+=dt;
 if(film){let t=(now-film.start)/35000;let target;if(t<.09)target=hero.offsetHeight*Math.pow(t/.09,2);else target=cinematic.offsetTop+(cinematic.offsetHeight-innerHeight)*clamp((t-.09)/.86);window.scrollTo({top:target,behavior:'instant'});if(t>=1){stopFilm();scrollToTarget('#pendidikan');}dirty=true;}
 const target=clamp((scrollY-cinematic.offsetTop)/Math.max(1,cinematic.offsetHeight-innerHeight));
 const p=cinema.update(target,dt,!reduced&&!paused);metrics.cinemaProgress=p;metrics.video=cinema.ready;metrics.frames=cinema.metrics.frames;updateShot(p);
 let needsPaint=dirty||(!(reduced||paused)&&now-lastPaint>34);if(!needsPaint)return;
 if(heroVisible&&land){land.zoom=clamp(scrollY/hero.offsetHeight);land.render(clock);}
 if(dayVisible&&dayland)dayland.render(clock);
 if(dirty&&!reduced&&!paused){const r=$('.documentary').getBoundingClientRect();if(r.top<innerHeight&&r.bottom>0)$('.documentary-photo').style.transform=`translateY(${clamp((innerHeight/2-r.top)/innerHeight,-1,1)*22}px)`;}
 lastPaint=now;dirty=false;
}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&film)film.hiddenAt=performance.now();else if(film?.hiddenAt){film.start+=performance.now()-film.hiddenAt;film.hiddenAt=null;}dirty=true;lastTime=performance.now();});
window.addEventListener('pagehide',()=>{stopFilm();});
onScroll();requestAnimationFrame(tick);
})();
