/* Assyabab Atelier — purpose-built WebGL2 renderer. No runtime dependencies. */
(() => {
'use strict';
const PI=Math.PI,TAU=PI*2;
const M={
 identity:()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),
 mul:(a,b)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;},
 translate:(x,y,z)=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,x,y,z,1]),
 scale:(x,y=x,z=x)=>new Float32Array([x,0,0,0,0,y,0,0,0,0,z,0,0,0,0,1]),
 rx:a=>{let c=Math.cos(a),s=Math.sin(a);return new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1]);},
 ry:a=>{let c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,0,0,0,1]);},
 rz:a=>{let c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,s,0,0,-s,c,0,0,0,0,1,0,0,0,0,1]);},
 perspective:(f,aspect,near=.1,far=200)=>{let t=1/Math.tan(f/2);return new Float32Array([t/aspect,0,0,0,0,t,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);},
 ortho:(l,r,b,t,n,f)=>new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]),
 lookAt:(eye,target,up=[0,1,0])=>{const norm=v=>{let d=Math.hypot(...v)||1;return v.map(x=>x/d);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((v,n,i)=>v+n*b[i],0);let z=norm(eye.map((v,i)=>v-target[i])),x=norm(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);},
 compose:(p=[0,0,0],r=[0,0,0],s=[1,1,1])=>M.mul(M.mul(M.mul(M.mul(M.translate(...p),M.ry(r[1])),M.rx(r[0])),M.rz(r[2])),M.scale(...s))
};
const mix=(a,b,t)=>a+(b-a)*t,clamp=(x,a=0,b=1)=>Math.min(b,Math.max(a,x)),smooth=(a,b,x)=>{x=clamp((x-a)/(b-a));return x*x*(3-2*x);};
const rand=(seed=431)=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};
const color=hex=>{let s=hex.replace('#','');return [0,2,4].map(i=>parseInt(s.slice(i,i+2),16)/255);};
class Geometry {
 constructor(){this.v=[];}
 tri(a,b,c,uvs){const u=b.map((n,i)=>n-a[i]),v=c.map((n,i)=>n-a[i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],d=Math.hypot(...n)||1;n=n.map(x=>x/d);[a,b,c].forEach((p,i)=>this.v.push(...p,...n,...(uvs?.[i]||[i===1?1:0,i===2?1:0])));return this;}
 quad(a,b,c,d,uv=[[0,0],[1,0],[1,1],[0,1]]){return this.tri(a,b,c,[uv[0],uv[1],uv[2]]).tri(a,c,d,[uv[0],uv[2],uv[3]]);}
 box(x=1,y=1,z=1,at=[0,0,0]){const [cx,cy,cz]=at,X=x/2,Y=y/2,Z=z/2;const p=(a,b,c)=>[a*X+cx,b*Y+cy,c*Z+cz];this.quad(p(-1,-1,1),p(1,-1,1),p(1,1,1),p(-1,1,1));this.quad(p(1,-1,-1),p(-1,-1,-1),p(-1,1,-1),p(1,1,-1));this.quad(p(-1,-1,-1),p(-1,-1,1),p(-1,1,1),p(-1,1,-1));this.quad(p(1,-1,1),p(1,-1,-1),p(1,1,-1),p(1,1,1));this.quad(p(-1,1,1),p(1,1,1),p(1,1,-1),p(-1,1,-1));this.quad(p(-1,-1,-1),p(1,-1,-1),p(1,-1,1),p(-1,-1,1));return this;}
 cylinder(rt=1,rb=1,h=1,segments=48,at=[0,0,0]){let p=(r,a,y)=>[at[0]+r*Math.cos(a),at[1]+y,at[2]+r*Math.sin(a)];for(let i=0;i<segments;i++){let a=i/segments*TAU,b=(i+1)/segments*TAU;this.quad(p(rb,b,-h/2),p(rb,a,-h/2),p(rt,a,h/2),p(rt,b,h/2));if(rt)this.tri(p(0,0,h/2),p(rt,b,h/2),p(rt,a,h/2));if(rb)this.tri(p(0,0,-h/2),p(rb,a,-h/2),p(rb,b,-h/2));}return this;}
 plane(w=1,h=1,nx=1,ny=1){for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const p=(u,v)=>[(u-.5)*w,0,(v-.5)*h];let u=x/nx,v=y/ny,U=(x+1)/nx,V=(y+1)/ny;this.quad(p(u,V),p(U,V),p(U,v),p(u,v),[[u,1-V],[U,1-V],[U,1-v],[u,1-v]]);}return this;}
 tube(points,r=.015,sides=5){for(let i=0;i<points.length-1;i++){let a=points[i],b=points[i+1],d=b.map((v,k)=>v-a[k]),l=Math.hypot(...d);if(l<1e-8)continue;d=d.map(x=>x/l);let t=Math.abs(d[1])>.9?[1,0,0]:[0,1,0],u=[d[1]*t[2]-d[2]*t[1],d[2]*t[0]-d[0]*t[2],d[0]*t[1]-d[1]*t[0]],q=Math.hypot(...u);u=u.map(x=>x/q);let v=[d[1]*u[2]-d[2]*u[1],d[2]*u[0]-d[0]*u[2],d[0]*u[1]-d[1]*u[0]];const p=(c,an)=>c.map((x,k)=>x+r*(Math.cos(an)*u[k]+Math.sin(an)*v[k]));for(let j=0;j<sides;j++)this.quad(p(a,j/sides*TAU),p(a,(j+1)/sides*TAU),p(b,(j+1)/sides*TAU),p(b,j/sides*TAU));}return this;}
}
const vertex=`#version 300 es
precision highp float;
layout(location=0) in vec3 aPosition;layout(location=1) in vec3 aNormal;layout(location=2) in vec2 aUv;
uniform mat4 uModel,uVP,uLightVP,uReflectionVP;uniform float uTime,uWind,uCurl;
out vec3 vPos,vNormal;out vec2 vUv;out vec4 vShadow,vReflection;
void main(){vec3 p=aPosition;vec3 n=aNormal;
 if(uWind>0.){float w=sin(uTime*.65+p.x*.7+p.z*.5);p.x+=w*.042*aUv.y*uWind;p.z+=cos(uTime*.42+p.x)*.020*aUv.y*uWind;}
 if(abs(uCurl)>.0001){p.y+=sin(aUv.x*3.14159265)*uCurl;n=normalize(vec3(-cos(aUv.x*3.14159265)*uCurl*1.8,1.,0.));}
 vec4 world=uModel*vec4(p,1.);vPos=world.xyz;vNormal=normalize(transpose(inverse(mat3(uModel)))*n);vUv=aUv;vShadow=uLightVP*world;vReflection=uReflectionVP*world;gl_Position=uVP*world;}`;
const fragment=`#version 300 es
precision highp float;in vec3 vPos,vNormal;in vec2 vUv;in vec4 vShadow,vReflection;
uniform vec3 uColor,uEye,uKey,uFogColor,uGlow;uniform float uMetal,uRough,uEmission,uAlpha,uFog,uTextureMix,uMode,uTime,uShadowOn,uReflectionOn;uniform sampler2D uMap,uShadowMap,uReflectionMap;
out vec4 frag;
float shadow(){vec3 p=vShadow.xyz/vShadow.w*.5+.5;if(p.x<0.||p.x>1.||p.y<0.||p.y>1.||p.z>1.)return 1.;float s=0.;for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float d=texture(uShadowMap,p.xy+vec2(float(x),float(y))/1536.).r;s+=p.z-.0018<=d?1.:.26;}return mix(1.,s/9.,uShadowOn);}
float hash(vec3 p){return fract(sin(dot(p,vec3(12.9898,78.233,42.1)))*43758.5453);}
void main(){vec3 n=normalize(vNormal)*(gl_FrontFacing?1.:-1.);vec3 view=normalize(uEye-vPos);vec4 sampled=texture(uMap,vUv);if(uMode==4.&&sampled.a<.45)discard;vec3 tex=sampled.rgb;vec3 albedo=uColor*mix(vec3(1.),tex,uTextureMix);float gold=smoothstep(.44,.7,tex.r)*uTextureMix;float met=uMetal;vec3 l=uMode>=3.?normalize(vec3(-.5,.8,.3)):normalize(vec3(-4.,7.,3.)-vPos);float diffuse=max(dot(n,l),0.);float hemi=mix(.20,.55,n.y*.5+.5);float sh=shadow();vec3 lit=albedo*(vec3(.55,.64,.65)*hemi+uKey*diffuse*sh*.93);float spec=pow(max(dot(n,normalize(l+view)),0.),mix(95.,12.,uRough));lit+=mix(vec3(.10),albedo,met)*spec*sh*(.8+met*1.8)*uKey;
 float rim=pow(1.-max(dot(n,view),0.),3.);lit+=vec3(.095,.14,.14)*rim*.5; vec3 glowDir=vec3(0.,1.7,0.)-vPos;float gd=length(glowDir);lit+=albedo*uGlow*max(dot(n,normalize(glowDir)),0.)/(.5+gd*gd)*1.3;
 if(uMode==1.){float veins=sin(vPos.x*3.+vPos.z*.45+sin(vPos.z*2.)*.7+sin(vPos.x*7.));lit+=vec3(.026,.032,.030)*pow(abs(veins),22.);vec2 rp=vReflection.xy/vReflection.w*.5+.5;rp+=vec2(sin(vPos.z*5.+uTime*.08),cos(vPos.x*3.))*.0009;float fresnel=.15+.3*pow(1.-max(dot(n,view),0.),3.);vec3 refl=texture(uReflectionMap,clamp(rp,.001,.999)).rgb;lit=mix(lit,refl,fresnel*uReflectionOn);}
 lit+=albedo*uEmission;lit=lit/(1.+max(lit-.92,0.));float alpha=uAlpha;
 if(uMode==2.){float edge=pow(max(sin(vUv.x*3.14159265),0.),2.);alpha*=edge*pow(max(sin(vUv.y*3.14159265),0.),.6);lit=uColor*(1.+uEmission);}
 float fog=1.-exp(-length(uEye-vPos)*uFog);lit=mix(lit,uFogColor,fog);frag=vec4(lit,alpha);}`;
const depthFrag=`#version 300 es
precision highp float;out vec4 frag;void main(){frag=vec4(1.);}`;
const quadVert=`#version 300 es
precision highp float;layout(location=0) in vec2 aPos;out vec2 vUv;void main(){vUv=aPos*.5+.5;gl_Position=vec4(aPos,0.,1.);}`;
const postFrag=`#version 300 es
precision highp float;in vec2 vUv;out vec4 frag;uniform sampler2D uScene;uniform vec2 uResolution;uniform float uPortal,uTime,uBloom;
vec3 glow(vec2 uv){vec3 c=texture(uScene,uv).rgb;return max(c-vec3(.64),vec3(0.));}
void main(){vec2 uv=vUv;vec3 c=texture(uScene,uv).rgb,b=vec3(0.);for(int i=0;i<12;i++){float a=float(i)*.523598;vec2 d=vec2(cos(a),sin(a));b+=glow(uv+d*.004)+glow(uv+d*.012)*.8+glow(uv+d*.023)*.5;}c+=b/20.*uBloom;float vig=smoothstep(.18,.82,length((uv-.5)*vec2(1.1,1.)));c*=1.-vig*.24;float grain=fract(sin(dot(uv*uResolution+uTime*.2,vec2(12.9898,78.233)))*43758.5453)-.5;c+=grain*.012;float dist=length((uv-.5)*vec2(uResolution.x/uResolution.y,1.));float portal=clamp((uPortal-dist*.12)*1.4,0.,1.);float cells=mix(220.,35.,uPortal);vec2 cell=floor(uv*cells);float dith=fract(sin(dot(cell,vec2(19.31,73.77)))*45758.12);float reveal=smoothstep(dith*.42,dith*.42+.58,portal);c=mix(c,vec3(.91,.86,.72),reveal);frag=vec4(c,1.);}`;
const particleV=`#version 300 es
precision highp float;layout(location=0)in vec4 aSeed;uniform mat4 uVP;uniform float uTime,uEnergy,uPixelRatio;out float vAlpha;out vec3 vColor;void main(){float a=aSeed.x*6.2831853+uTime*(.10+aSeed.w*.11);float radius=mix(6.,1.4+aSeed.z*.9,uEnergy);vec3 p=vec3(cos(a)*radius,(aSeed.y*4.+uTime*.13*(1.+aSeed.w)) ,sin(a)*radius);p.y=mod(p.y,4.)+.35;p.x+=sin(p.y*1.7+uTime*.2)*.15;p.z+=cos(p.y*1.3)*.2;vec4 clip=uVP*vec4(p,1.);gl_Position=clip;gl_PointSize=clamp((1.5+aSeed.w*4.)*uPixelRatio*6./max(clip.w,1.),1.,10.);vAlpha=(.10+aSeed.z*.45)*(1.-smoothstep(3.5,4.35,p.y));vColor=mix(vec3(.64,.7,.6),vec3(1.,.77,.32),aSeed.w);}`;
const particleF=`#version 300 es
precision highp float;in float vAlpha;in vec3 vColor;out vec4 frag;void main(){float d=length(gl_PointCoord-.5);float a=exp(-d*d*22.)*vAlpha;if(d>.5)discard;frag=vec4(vColor*1.8,a);}`;
class Renderer {
 constructor(canvas){
  this.canvas=canvas;const gl=canvas.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});if(!gl)throw new Error('WebGL2 tidak tersedia');this.gl=gl;this.program=this.compile(vertex,fragment);this.depthProgram=this.compile(vertex,depthFrag);this.post=this.compile(quadVert,postFrag);this.particleProgram=this.compile(particleV,particleF);this.meshes=[];this.buffers=[];this.textures=[];this.frames=0;this.lost=false;
  this.white=this.texture(new Uint8Array([255,255,255,255]),1,1);this.shadow=this.target(1536,1536,true);this.reflection=this.target(640,640);this.frame=this.target(16,16);this.multi=null;this.lightVP=M.mul(M.ortho(-8,8,-8,8,.1,30),M.lookAt([-4,9,4],[0,1,0]));this.quad=gl.createVertexArray();gl.bindVertexArray(this.quad);let q=gl.createBuffer();this.buffers.push(q);gl.bindBuffer(gl.ARRAY_BUFFER,q);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);gl.bindVertexArray(null);
  let rng=rand(234),seeds=new Float32Array(1000*4);for(let i=0;i<seeds.length;i++)seeds[i]=rng();this.particleVao=gl.createVertexArray();gl.bindVertexArray(this.particleVao);let pb=gl.createBuffer();this.buffers.push(pb);gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,seeds,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,0,0);gl.bindVertexArray(null);this.particleCount=1000;
  this.onLost=e=>{e.preventDefault();this.lost=true;canvas.dispatchEvent(new CustomEvent('scene-lost'));};this.onRestored=()=>{canvas.dispatchEvent(new CustomEvent('scene-restored'));};canvas.addEventListener('webglcontextlost',this.onLost);canvas.addEventListener('webglcontextrestored',this.onRestored);
 }
 compile(v,f){const gl=this.gl,p=gl.createProgram();for(let [type,code]of[[gl.VERTEX_SHADER,v],[gl.FRAGMENT_SHADER,f]]){const s=gl.createShader(type);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const error=gl.getShaderInfoLog(s);gl.deleteShader(s);gl.deleteProgram(p);throw new Error(error);}gl.attachShader(p,s);gl.deleteShader(s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return {p,loc:{}};}
 uniform(p,name,value){const gl=this.gl;let loc=p.loc[name];if(loc===undefined)loc=p.loc[name]=gl.getUniformLocation(p.p,name);if(loc===null)return;if(typeof value==='number')gl.uniform1f(loc,value);else if(value.length===16)gl.uniformMatrix4fv(loc,false,value);else if(value.length===3)gl.uniform3fv(loc,value);else if(value.length===2)gl.uniform2fv(loc,value);}
 sampler(p,name,texture,unit){const gl=this.gl;let loc=p.loc[name];if(loc===undefined)loc=p.loc[name]=gl.getUniformLocation(p.p,name);gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,texture);if(loc!==null)gl.uniform1i(loc,unit);}
 texture(data,w,h){const gl=this.gl,t=gl.createTexture();this.textures.push(t);gl.bindTexture(gl.TEXTURE_2D,t);if(w)gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,data);else{gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,data);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);}gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t;}
 target(w,h,shadow=false){const gl=this.gl,fbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fbo);let tex=gl.createTexture();this.textures.push(tex);gl.bindTexture(gl.TEXTURE_2D,tex);if(shadow)gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,w,h,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);else gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,shadow?gl.NEAREST:gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,shadow?gl.NEAREST:gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.framebufferTexture2D(gl.FRAMEBUFFER,shadow?gl.DEPTH_ATTACHMENT:gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);let depth=null;if(shadow){gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);}else{depth=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,depth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,w,h);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,depth);}if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error('Framebuffer tidak lengkap');gl.bindFramebuffer(gl.FRAMEBUFFER,null);return {fbo,tex,depth,w,h};}
 multisample(w,h){const gl=this.gl,fbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fbo);let buffers=[];for(let [format,attachment]of[[gl.RGBA8,gl.COLOR_ATTACHMENT0],[gl.DEPTH_COMPONENT24,gl.DEPTH_ATTACHMENT]]){let rb=gl.createRenderbuffer();buffers.push(rb);gl.bindRenderbuffer(gl.RENDERBUFFER,rb);gl.renderbufferStorageMultisample(gl.RENDERBUFFER,Math.min(4,gl.getParameter(gl.MAX_SAMPLES)),format,w,h);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,attachment,gl.RENDERBUFFER,rb);}if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error("Multisample framebuffer tidak lengkap");gl.bindFramebuffer(gl.FRAMEBUFFER,null);return {fbo,buffers};}
 resize(w,h,quality=1){const gl=this.gl;this.ratio=Math.min(devicePixelRatio||1,quality>1?2:1.5);this.width=Math.max(1,Math.round(w*this.ratio));this.height=Math.max(1,Math.round(h*this.ratio));if(this.width===this.canvas.width&&this.height===this.canvas.height)return;this.canvas.width=this.width;this.canvas.height=this.height;gl.deleteFramebuffer(this.frame.fbo);gl.deleteRenderbuffer(this.frame.depth);gl.deleteTexture(this.frame.tex);this.textures=this.textures.filter(t=>t!==this.frame.tex);this.frame=this.target(this.width,this.height);if(this.multi){gl.deleteFramebuffer(this.multi.fbo);this.multi.buffers.forEach(b=>gl.deleteRenderbuffer(b));}try{this.multi=this.multisample(this.width,this.height);}catch{this.multi=null;}}
 mesh(geo,opts={}){const gl=this.gl,vao=gl.createVertexArray(),buffer=gl.createBuffer();this.buffers.push(buffer);gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(geo.v),gl.STATIC_DRAW);for(let [loc,len,off] of[[0,3,0],[1,3,12],[2,2,24]]){gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,len,gl.FLOAT,false,32,off);}gl.bindVertexArray(null);let m={vao,count:geo.v.length/8,matrix:M.identity(),color:color('587065'),rough:.6,metal:0,emission:0,alpha:1,wind:0,curl:0,mode:0,visible:true,shadow:true,...opts};this.meshes.push(m);return m;}
 draw(meshes,p,vp,env,shadow=false){const gl=this.gl;gl.useProgram(p.p);const u=(n,v)=>this.uniform(p,n,v);u('uVP',vp);u('uLightVP',this.lightVP);u('uReflectionVP',env.refVP||M.identity());u('uTime',env.time);if(!shadow){u('uEye',env.eye);u('uKey',env.key||[1,.84,.57]);u('uFogColor',env.fogColor||[.025,.045,.037]);u('uFog',env.fog??.025);u('uGlow',env.glow||[0,0,0]);u('uShadowOn',env.shadows?1:0);u('uReflectionOn',env.reflect?1:0);this.sampler(p,'uShadowMap',this.shadow.tex,1);this.sampler(p,'uReflectionMap',env.reflect?this.reflection.tex:this.white,2);}
  for(const m of [...meshes.filter(m=>m.alpha>=1),...meshes.filter(m=>m.alpha<1)]){if(!m.visible||m.alpha<=.001||shadow&&(!m.shadow||m.alpha<1)||env.skipFloor&&m.mode===1)continue;u('uModel',m.matrix);u('uWind',m.wind);u('uCurl',m.curl);if(!shadow){u('uColor',m.color);u('uMetal',m.metal);u('uRough',m.rough);u('uEmission',m.emission);u('uAlpha',m.alpha);u('uMode',m.mode);u('uTextureMix',m.texture?1:0);this.sampler(p,'uMap',m.texture||this.white,0);if(m.alpha<1){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,m.additive?gl.ONE:gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);}else{gl.disable(gl.BLEND);gl.depthMask(true);}}
   gl.bindVertexArray(m.vao);gl.drawArrays(gl.TRIANGLES,0,m.count);
  }gl.bindVertexArray(null);gl.depthMask(true);gl.disable(gl.BLEND);
 }
 render(meshes,env){if(this.lost)return;const gl=this.gl;this.frames++;const vp=M.mul(M.perspective(env.fov||.66,this.width/this.height,.1,180),M.lookAt(env.eye,env.target));gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.depthMask(true);
  if(env.shadows){gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadow.fbo);gl.viewport(0,0,this.shadow.w,this.shadow.h);gl.clear(gl.DEPTH_BUFFER_BIT);this.draw(meshes,this.depthProgram,this.lightVP,env,true);}
  if(env.reflect){const eye=[env.eye[0],-env.eye[1],env.eye[2]],target=[env.target[0],-env.target[1],env.target[2]];env.refVP=M.mul(M.perspective(env.fov||.66,this.width/this.height,.1,180),M.lookAt(eye,target,[0,-1,0]));gl.bindFramebuffer(gl.FRAMEBUFFER,this.reflection.fbo);gl.viewport(0,0,this.reflection.w,this.reflection.h);gl.clearColor(...env.fogColor,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.draw(meshes,this.program,env.refVP,{...env,eye,reflect:false,skipFloor:true});}
  gl.bindFramebuffer(gl.FRAMEBUFFER,this.multi?this.multi.fbo:this.frame.fbo);gl.viewport(0,0,this.width,this.height);gl.clearColor(...env.fogColor,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.draw(meshes,this.program,vp,env);
  if(env.particles){let p=this.particleProgram;gl.useProgram(p.p);this.uniform(p,'uVP',vp);this.uniform(p,'uTime',env.time);this.uniform(p,'uEnergy',env.energy||0);this.uniform(p,'uPixelRatio',this.ratio);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.depthMask(false);gl.bindVertexArray(this.particleVao);gl.drawArrays(gl.POINTS,0,this.particleCount);gl.bindVertexArray(null);gl.disable(gl.BLEND);gl.depthMask(true);}
  if(this.multi){gl.bindFramebuffer(gl.READ_FRAMEBUFFER,this.multi.fbo);gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER,this.frame.fbo);gl.blitFramebuffer(0,0,this.width,this.height,0,0,this.width,this.height,gl.COLOR_BUFFER_BIT,gl.NEAREST);}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.width,this.height);gl.disable(gl.DEPTH_TEST);gl.useProgram(this.post.p);this.sampler(this.post,'uScene',this.frame.tex,0);this.uniform(this.post,'uResolution',[this.width,this.height]);this.uniform(this.post,'uTime',env.time);this.uniform(this.post,'uPortal',env.portal||0);this.uniform(this.post,'uBloom',env.bloom??.5);gl.bindVertexArray(this.quad);gl.drawArrays(gl.TRIANGLES,0,6);gl.bindVertexArray(null);
 }
 dispose(){const gl=this.gl;this.canvas.removeEventListener('webglcontextlost',this.onLost);this.canvas.removeEventListener('webglcontextrestored',this.onRestored);for(let m of this.meshes)gl.deleteVertexArray(m.vao);for(let b of this.buffers)gl.deleteBuffer(b);for(let t of this.textures)gl.deleteTexture(t);for(let t of[this.shadow,this.reflection,this.frame]){gl.deleteFramebuffer(t.fbo);if(t.depth)gl.deleteRenderbuffer(t.depth);}if(this.multi){gl.deleteFramebuffer(this.multi.fbo);this.multi.buffers.forEach(b=>gl.deleteRenderbuffer(b));}for(let p of[this.program,this.depthProgram,this.post,this.particleProgram])gl.deleteProgram(p.p);gl.deleteVertexArray(this.quad);gl.deleteVertexArray(this.particleVao);}
}
window.A3D={M,Geometry,Renderer,PI,TAU,mix,clamp,smooth,rand,color};
})();
